#!/bin/bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

set -eu

######################
# Setting YADM stuff
######################
function yadm_getrel () {
    yadm_root=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    echo $1 | sed -e "s|^${yadm_root}/||" -e 's|.*/\([^/]*/[^/]*\)$|\1|'
}
export -f yadm_getrel

function yadm_startscript () {
    echo "script-start: $(yadm_getrel $0)"
}
export -f yadm_startscript

function yadm_endscript () {
    echo "script-end: $(yadm_getrel $0)"
}
export -f yadm_endscript

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

declare -a bootstraps
while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ ~$ ]]; then
        bootstraps+=("$bootstrap")
    fi
done < <(find -L "$BOOTSTRAP_D" -type f | sort)

for bootstrap in "${bootstraps[@]}"; do
    if ! "$bootstrap"; then
        echo "Error: bootstrap '$bootstrap' failed" >&2
        exit 1
    fi
done
